---
title: May Recap - Diversity in Data
author: R Ladies Philly
date: '2019-06-10'
slug: may-recap-diversity-data
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

# How to communicate as (minority) data scientists?

Being a minority in data science can be tough. It can be tough to get into the field, and sometimes even tougher to make yourself heard in the field. **Marieke Jackson**, a former epidemiologist turned data scientist, shared how basic rules from improv have helped her navigate day to day challenges. 

*Imagine you are working with an improv partner and you mention those pesky magical flying birds that poop jellybeans. And your partner says: “huh? We’re on a boat, on the moon - there are no birds here.”*

Your partner has blocked your attempt to share your reality, and this interrupts flow, makes communication difficult, and can make everyone seem a bit out of place. One of the core rules of improv is to listen to your partner in conversation, agree, and build upon the shared understanding. This holds in a meeting too: as data scientists, we should listen to the non-data people in the team and really pay attention when they explain what they do or what problems they face. As Marieke put it, “you have to be trusting of your partner, accept being vulnerable, be accepting of what they give you and be willing to build on top of it.” What you don’t want to do is tell them there are no magical birds that poop jelly beans (i.e., discount their perspective and expertise). Instead, what you should do is find ways to give things to your scene/meeting partner that make them look good - because if they look good, you look good, and the interaction flows, and everyone wins. 

# How do training institutions communicate with data science minorities?

**Jennifer Bochenek**, who has experience working with education services and is currently a data science graduate student, explored how educational institutions may attract (or not) diversity students through mission statements. 

Mission statements reflect an institution’s goals, values and aspirations, but are the words chosen just to secure accreditation, or do they truly reflect the atmosphere and orientation of the school? While back in the 1990s diversity was limited to racial and ethnic diversity only, nowadays the term has expanded to include other kinds of diverse characteristics as well, e.g. geography, gender identity, age or generation, religious and spiritual beliefs, etc. 

Looking specifically at gender diversity, Jennifer noted that while the number of women in colleges has increased dramatically in the last 60 years and women earn 58% of bachelor’s degrees, they only earn 35% of STEM degrees. In her study, she examined almost 800 mission statements from institutions conferring bachelor’s, master’s and doctoral degrees, and found that diversity was mentioned in only 17% of cases. Interestingly, mentioning diversity in the mission statement did not appear to be related to the number of women graduating with STEM degrees. However, programs that DO have greater numbers of women graduating with STEM degrees, tend to have mission statements that include words like “safe”, “moral”, “inclusive”, “supporting” and “collaborative”.  

# When should training institutions communicate with data science minorities?

According to **Danica Pascavage** of [TechGirlz](https://www.techgirlz.org/), the best time to get gender minorities excited about tech is middle school. She observed that interest in tech is fairly equally divided between genders until kids reach middle school, when girls seem to lose interest. 

She pointed out that the time when girls lose interest in tech is also the time when girls seek out opportunities to be nurturing, to collaborate with others and work towards the greater good. Danica thinks that one explanation for why girls are stepping away from tech and engineering in middle school is the cultural portrayal of people working in tech. Media often shows tech savvy individuals as hackers who work alone in dark rooms and are often up to no good. Which is the opposite of the social, collaborative, fun activities that girls seek at that age. 

Based on her experience with TechGirlz, Danica believes that if we want to increase diversity in tech and data science, we need to start in middle school, and we need to show girls that they can help others and collaborate with each other through technology. 

# Thank yous!

Many thanks to everyone who made this event possible!  We are very grateful to Liz Scott of [Alex’ Lemonade Stand Foundation (ALSF)](www.AlexsLemonade.org) and Jaclyn Taroni and Casey Green of the [Childhood Cancer Data Lab (CCDL; an ALSF initiative based in Philadelphia)](https://www.ccdatalab.org/) for providing location space. 

Alex's Lemonade Stand Foundation emerged from the front yard lemonade stand of 4-year-old Alexandra “Alex” Scott, who was fighting cancer and wanted to raise money to find cures for all children with cancer. Her spirit and determination inspired others to support her cause, and when she passed away at the age of 8, she had raised $1 million. Since then, the Foundation bearing her name has evolved into a national fundraising movement. Today, ALSF is one of the leading funders of pediatric cancer research in the U.S. and Canada having raised more than $150 million so far, funding nearly 1,000 research projects and providing programs to families affected by childhood cancer. For more information, visit [AlexsLemonade.org](www.AlexsLemonade.org).

We also enjoyed partnering with [Accenture](https://www.accenture.com/us-en)'s Philly Metro Women’s Interest Employee Resource Group for this event. Special thanks to Jade Jackson, Erin Senker, and Donna Delrieu. Finally, many thanks to our speakers: Marieke Jackson, Jennifer Bochenek, and Danica Pascavage.

# Announcements

* R-Ladies Philly and the broader Philly data science community will converge at the [DataJawn](https://www.thedatalab.io/the-data-jawn) on June 12th. We hope to see everyone there! 
* Code for Philly is working on a project to help Philadelphia Lawyers for Social Equity (PLSE), a non-profit legal aid organization that focuses on helping people overcome the barriers they face as a result of criminal records. (reach out to the organizers of [this event](https://www.meetup.com/Code-for-Philly/events/258479747/) to join!)
* Michael Becker (of Data Philly) is doing a project for the DataJawn about becoming a data scientist. Make sure to fill out [this survey](https://docs.google.com/forms/d/e/1FAIpQLSfw6j7szKGMRbgp07OcXauR4qlbTQhhRxFjVmh3wWm_3YUguQ/viewform) before the event! 
* There are free improv classes available through [PHIT](https://phillyimprovtheater.com/classes-old/free-intro-workshops/)
* Accenture is hiring! Go to [this site](https://www.accenture.com/us-en/careers/jobsearch) to search the most recent listings!
* CCDL is hiring! Check out their open poistions [here](https://www.ccdatalab.org/careers)

